// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePayment = "payments"

// Payment mapped from table <payments>
type Payment struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PaymentID     string    `gorm:"column:payment_id;not null" json:"payment_id"`
	UserID        string    `gorm:"column:user_id;not null" json:"user_id"`
	Amount        *int32    `gorm:"column:amount" json:"amount"`
	Remarks       *string   `gorm:"column:remarks" json:"remarks"`
	BalanceBefore int32     `gorm:"column:balance_before;not null" json:"balance_before"`
	BalanceAfter  int32     `gorm:"column:balance_after;not null" json:"balance_after"`
	CreatedDate   time.Time `gorm:"column:created_date;not null" json:"created_date"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
