// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransfer = "transfer"

// Transfer mapped from table <transfer>
type Transfer struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TransferID    string    `gorm:"column:transfer_id;not null" json:"transfer_id"`
	UserID        string    `gorm:"column:user_id;not null" json:"user_id"`
	Amount        int32     `gorm:"column:amount;not null" json:"amount"`
	Remarks       *string   `gorm:"column:remarks" json:"remarks"`
	BalanceBefore int32     `gorm:"column:balance_before;not null" json:"balance_before"`
	BalanceAfter  int32     `gorm:"column:balance_after;not null" json:"balance_after"`
	CreatedDate   time.Time `gorm:"column:created_date;not null" json:"created_date"`
}

// TableName Transfer's table name
func (*Transfer) TableName() string {
	return TableNameTransfer
}
