// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID          int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      string     `gorm:"column:user_id;not null" json:"user_id"`
	FirstName   *string    `gorm:"column:first_name" json:"first_name"`
	LastName    *string    `gorm:"column:last_name" json:"last_name"`
	PhoneNumber *string    `gorm:"column:phone_number" json:"phone_number"`
	Address     *string    `gorm:"column:address" json:"address"`
	Pin         *string    `gorm:"column:pin" json:"pin"`
	CreatedAt   time.Time  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
